src/models/site.py
import CloudFlare

from src.common.utils import Utils
from src.common import errors as SiteError


class SiteModel:
    def __init__(self, name, _id):
        self.name = name
        self.id = _id
        self.environment = None

    def __repr__(self):
        return f'<Site {self.name}>'

    @classmethod
    def get_from_cloudflare(cls, _id=None):
        """
        Returns a list of SiteModel objects for all zones found in Cloudflare.
        If an id is passed returns a single instance of that zone
        """
        try:
            cf = CloudFlare.CloudFlare()
            zones = cf.zones.get(_id, params={'per_page': 100})
        except:
            raise SiteError.UnableToListSiteError(
                'Error occurred when trying to retrieve the sites')

        return cls(zones['name'], zones['id']) if _id else \
            [cls(zone['name'], zone['id']) for zone in zones]

    @staticmethod
    def get_sites():
        """
        Returns a list of SiteModel objects with the environment set
        """
        sites = SiteModel.get_from_cloudflare()
        for site in sites:
            if Utils.is_staging(site.name):
                site.environment = 'staging'
            else:
                site.environment = 'production'

        return sites

    @staticmethod
    def get_one_site(_id):
        """
        Takes a zone id and returns an instance of SiteModel
        """
        site = SiteModel.get_from_cloudflare(_id)

        return site

    def purge_all_cache(self):
        """
        Purges all files within a sites Cloudflare cache
        """
        if not Utils.is_staging(self.name):
            raise SiteError.NonStagingSiteError(
                f'Unable to preform action for {self.name}')
        try:
            cf = CloudFlare.CloudFlare()
            cf.zones.purge_cache.delete(self.id,
                                        data={'purge_everything': True})
        except:
            raise SiteError.UnableToPurgeCacheError(
                'Error occured when trying to purge the cache')

    def purge_items_in_cache(self, urls):
        """
        Purges indiviual files within a sites Cloudflare cache
        """
        valid_urls = [url for url in urls
                      if Utils.url_matches_site_name(self.name, url)]
        if valid_urls:
            try:
                cf = CloudFlare.CloudFlare()
                cf.zones.purge_cache.delete(self.id, data={'files': valid_urls})
            except:
                raise SiteError.UnableToPurgeCacheError(
                    'Error occured while trying to purge the cache')

        return valid_urls

    @staticmethod
    def purge_all_staging_cache():
        """
        Purges the entire cache for all staging sites
        """
        staging_sites = [site for site in SiteModel.get_sites()
                         if Utils.is_staging(site.name)]
        for site in staging_sites:
            print(f'Purging cache for {site}')
            site.purge_all_cache()

src/app.py
from flask import Flask

from src.views.site import site_blueprint


app = Flask(__name__)
app.config.from_object('config')
app.register_blueprint(site_blueprint)

src/views/site.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from webargs.flaskparser import use_args

from src.common.errors import SiteError
from src.models.site import SiteModel
from src.arguments.argument import Argument

site_blueprint = Blueprint('sites', __name__, template_folder='templates')


@site_blueprint.route('/')
def index():
    try:
        sites = SiteModel.get_sites()
    except SiteError as e:
        return e.message

    return render_template('index.html', sites=sites)


@site_blueprint.route('/purge-site', methods=['POST'])
@use_args(Argument.all_items_in_cache)
def purge_all_items_in_cache(args):
    try:
        site = SiteModel.get_one_site(**args)
        site.purge_all_cache()
    except SiteError as e:
        return e.message

    flash(f'Cache successfully cleared for {site.name}')

    return redirect(url_for('.index'))


@site_blueprint.route('/purge-items', methods=['POST'])
@use_args(Argument.single_items_in_cache)
def purge_single_items_in_cache(args):
    if args['urls'] == '':
        flash('Enter at least one URL')
        return redirect(url_for('.index'))

    try:
        site = SiteModel.get_one_site(args['_id'])
        urls = args['urls'].splitlines()
        purged_urls = site.purge_items_in_cache(urls)

    except SiteError as e:
        return e.message

    if purged_urls:
        flash(f'The following cached files were cleared for {site.name}')
        for url in purged_urls:
            flash(url)
    else:
        flash(f'Cache not purged! No valid urls were entered.')

    return redirect(url_for('.index'))


@site_blueprint.route('/purge-staging', methods=['POST'])
def purge_all_staging_cache():
    try:
        SiteModel.purge_all_staging_cache()
    except SiteError as e:
        return e.message

    flash('Cache successfully cleared for all staging sites')

    return redirect(url_for('.index'))

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>CF Buster 2.0</title>
</head>
<body>
<div class="container">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4 text-center">CF Buster 2.0</h1>
        </div>
    </div>
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
</body>
</html>

src/templates/index.html
{% extends "base.html" %}
{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{ message }}
                    <br/>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('sites.purge_all_items_in_cache') }}" role="form" method="POST">
        <div class="form-row">
            <label for="purgeAllItemsInCache">Clear a staging sites entire cache.</label>
            <div class="col-auto">
                <select class="form-control" name="_id" id="purgeAllItemsInCache">
                    {% for site in sites %}
                        {% if site.environment == 'staging' %}
                            <option value="{{ site.id }}">{{ site.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-danger"><i class="fab fa-hotjar"></i> Purge Cache</button>
            </div>
        </div>
    </form>

    <hr/>

    <form action="{{ url_for('sites.purge_all_staging_cache') }}" role="form" method="POST">
        <div class="form-row">
            <div class="col-auto">
                <label for="purgeAllStagingCache"><strong>Clear the cache for all staging sites.</strong></label>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-danger"><i class="fab fa-hotjar"></i> Purge Cache</button>
            </div>
        </div>
    </form>

    <hr/>

    <form action="{{ url_for('sites.purge_single_items_in_cache') }}" role="form" method="POST">
        <div class="form-group">
            <label for="purgeSingleItemsInCache">Clear individual files in a selected sites cache.</label>
            <select class="form-control" name="_id" id="purgeSingleItemsInCache">
                {% for site in sites %}
                    <option value="{{ site.id }}">{{ site.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="purgeSingleItemsInCacheTextArea">Enter one URL per line. It needs to match the selected site</label>
            <textarea name="urls" class="form-control" placeholder="http://site.com/path/to/file.jpeg"
                      id="purgeSingleItemsInCacheTextArea" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-danger"><i class="fab fa-hotjar"></i> Purge Cache</button>
    </form>
{% endblock %}